version: '3.8'

services:
  db:
    build: ./db
    container_name: operations_db
    restart: always
    environment: 
      POSTGRES_USER: unicorn_admin
      POSTGRES_PASSWORD: unicorn_password
      POSTGRES_DB: operations
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  flight_status_data_gen:
    build: ./flight_status_data_gen
    container_name: flight_status_data_gen
    restart: always
    depends_on:
      - db
    volumes:
      - shared_data:/shared_data

  jouney_data_gen:
    build: ./journey_generator
    container_name: jouney_data_gen
    restart: "no"
    depends_on:
      - db
  flight_status_data_extract:
    build: ./flight_status_data_extract
    container_name: flight_status_data_extract
    restart: "no"
    depends_on:
      - db
    volumes:
      - shared_data:/shared_data
  api:
    build: ./flight_status_api
    container_name: python_api
    ports:
      - "8000:8000"
    depends_on:
      - db
  internal_dashboard:
    build:
      context: ./internal_dashboard
    container_name: internal_dashboard
    ports:
      - "8501:8501"
    depends_on:
      - flight_status_data_extract

  airport_dashboard:
    build:
      context: ./airport_dashboard
    container_name: airport_dashboard
    ports:
      - "8502:8502"
    depends_on:
      - flight_status_data_extract
  customer_notifier:
    build: ./customer_notifier
    container_name: customer_notifier
    depends_on:
      - api

volumes:
  postgres_data:
  shared_data: