-- SQLite
INSERT INTO plane (model, manufacturer, capacity, registration_number, status) VALUES
('A320', 'Airbus', 180, 'UA001', 'Active'),
('A321', 'Airbus', 220, 'UA002', 'Active'),
('B737-800', 'Boeing', 189, 'UA003', 'Active'),
('B747-400', 'Boeing', 416, 'UA004', 'Retired'),
('A350-900', 'Airbus', 325, 'UA005', 'Active'),
('B787-9', 'Boeing', 296, 'UA006', 'Active'),
('CRJ900', 'Bombardier', 90, 'UA007', 'Active'),
('E190', 'Embraer', 100, 'UA008', 'Active'),
('A330-300', 'Airbus', 277, 'UA009', 'Active'),
('B777-300ER', 'Boeing', 396, 'UA010', 'Active'),
('ATR 72', 'ATR', 72, 'UA011', 'Active'),
('A220-300', 'Airbus', 150, 'UA012', 'Active'),
('MD-88', 'McDonnell Douglas', 149, 'UA013', 'Retired'),
('A310', 'Airbus', 280, 'UA014', 'Retired'),
('B757-300', 'Boeing', 243, 'UA015', 'Under Maintenance'),
('B767-300', 'Boeing', 269, 'UA016', 'Active'),
('E195', 'Embraer', 124, 'UA017', 'Active'),
('A318', 'Airbus', 132, 'UA018', 'Active'),
('B737 MAX 8', 'Boeing', 178, 'UA019', 'Active'),
('Superjet 100', 'Sukhoi', 98, 'UA020', 'Active'),
('DC-9', 'McDonnell Douglas', 139, 'UA021', 'Retired'),
('BAe 146', 'British Aerospace', 112, 'UA022', 'Retired'),
('A340-300', 'Airbus', 295, 'UA023', 'Under Maintenance'),
('B707', 'Boeing', 202, 'UA024', 'Retired'),
('B737-400', 'Boeing', 168, 'UA025', 'Active'),
('A380-800', 'Airbus', 853, 'UA026', 'Active'),
('Tu-154', 'Tupolev', 180, 'UA027', 'Retired'),
('Fokker 100', 'Fokker', 97, 'UA028', 'Retired'),
('Dash 8 Q400', 'Bombardier', 78, 'UA029', 'Active'),
('Il-96', 'Ilyushin', 262, 'UA030', 'Under Maintenance');

-- Inserting Data into Airport Table
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES
('LHR', 'Heathrow Airport', 'London', 'United Kingdom', 'Europe/London'),
('CDG', 'Charles de Gaulle Airport', 'Paris', 'France', 'Europe/Paris'),
('FRA', 'Frankfurt Airport', 'Frankfurt', 'Germany', 'Europe/Berlin'),
('AMS', 'Amsterdam Schiphol', 'Amsterdam', 'Netherlands', 'Europe/Amsterdam'),
('MAD', 'Adolfo Suárez Madrid–Barajas', 'Madrid', 'Spain', 'Europe/Madrid'),
('BCN', 'Barcelona–El Prat Airport', 'Barcelona', 'Spain', 'Europe/Madrid'),
('VIE', 'Vienna International Airport', 'Vienna', 'Austria', 'Europe/Vienna'),
('CPH', 'Copenhagen Airport', 'Copenhagen', 'Denmark', 'Europe/Copenhagen'),
('ARN', 'Stockholm Arlanda Airport', 'Stockholm', 'Sweden', 'Europe/Stockholm'),
('OSL', 'Oslo Gardermoen Airport', 'Oslo', 'Norway', 'Europe/Oslo'),
('DUB', 'Dublin Airport', 'Dublin', 'Ireland', 'Europe/Dublin'),
('BRU', 'Brussels Airport', 'Brussels', 'Belgium', 'Europe/Brussels'),
('ZRH', 'Zurich Airport', 'Zurich', 'Switzerland', 'Europe/Zurich'),
('PRG', 'Václav Havel Airport Prague', 'Prague', 'Czech Republic', 'Europe/Prague'),
('WAW', 'Warsaw Chopin Airport', 'Warsaw', 'Poland', 'Europe/Warsaw'),
('BUD', 'Budapest Airport', 'Budapest', 'Hungary', 'Europe/Budapest'),
('ATH', 'Athens International Airport', 'Athens', 'Greece', 'Europe/Athens'),
('HEL', 'Helsinki Airport', 'Helsinki', 'Finland', 'Europe/Helsinki'),
('LIS', 'Lisbon Airport', 'Lisbon', 'Portugal', 'Europe/Lisbon'),
('JFK', 'John F. Kennedy International', 'New York', 'USA', 'America/New_York'),
('DXB', 'Dubai International Airport', 'Dubai', 'UAE', 'Asia/Dubai'),
('HND', 'Tokyo Haneda Airport', 'Tokyo', 'Japan', 'Asia/Tokyo'),
('SIN', 'Singapore Changi Airport', 'Singapore', 'Singapore', 'Asia/Singapore'),
('SYD', 'Sydney Kingsford Smith Airport', 'Sydney', 'Australia', 'Australia/Sydney');
