INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('OSD', 'Åre Östersund Airport', 'Östersund', 'Sweden', 'Europe/Stockholm');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('LYS', 'Lyon–Saint-Exupéry Airport', 'Lyon', 'France', 'Europe/Paris');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('GVA', 'Geneva Airport', 'Geneva', 'Switzerland', 'Europe/Zurich');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('NCE', 'Nice Côte dAzur Airport', 'Nice', 'France', 'Europe/Paris');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('LED', 'Pulkovo Airport', 'Saint Petersburg', 'Russia', 'Europe/Moscow');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('SOF', 'Sofia Airport', 'Sofia', 'Bulgaria', 'Europe/Sofia');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('RIX', 'Riga International Airport', 'Riga', 'Latvia', 'Europe/Riga');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('TLL', 'Tallinn Airport', 'Tallinn', 'Estonia', 'Europe/Tallinn');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('VNO', 'Vilnius Airport', 'Vilnius', 'Lithuania', 'Europe/Vilnius');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('KRK', 'John Paul II International Airport', 'Kraków', 'Poland', 'Europe/Warsaw');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('PMI', 'Palma de Mallorca Airport', 'Palma', 'Spain', 'Europe/Madrid');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('SVG', 'Stavanger Airport', 'Stavanger', 'Norway', 'Europe/Oslo');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('GOT', 'Gothenburg Landvetter Airport', 'Gothenburg', 'Sweden', 'Europe/Stockholm');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('TSF', 'Treviso Airport', 'Treviso', 'Italy', 'Europe/Rome');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('MLA', 'Malta International Airport', 'Luqa', 'Malta', 'Europe/Malta');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('OTP', 'Henri Coandă International Airport', 'Bucharest', 'Romania', 'Europe/Bucharest');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('LUX', 'Luxembourg Airport', 'Luxembourg', 'Luxembourg', 'Europe/Luxembourg');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('SKG', 'Thessaloniki Airport', 'Thessaloniki', 'Greece', 'Europe/Athens');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('HER', 'Heraklion Airport', 'Heraklion', 'Greece', 'Europe/Athens');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('FAO', 'Faro Airport', 'Faro', 'Portugal', 'Europe/Lisbon');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('TXL', 'Berlin Tegel Airport', 'Berlin', 'Germany', 'Europe/Berlin');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('MUC', 'Munich Airport', 'Munich', 'Germany', 'Europe/Berlin');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('HAM', 'Hamburg Airport', 'Hamburg', 'Germany', 'Europe/Berlin');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('CGN', 'Cologne Bonn Airport', 'Cologne', 'Germany', 'Europe/Berlin');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('STR', 'Stuttgart Airport', 'Stuttgart', 'Germany', 'Europe/Berlin');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('DUS', 'Düsseldorf Airport', 'Düsseldorf', 'Germany', 'Europe/Berlin');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('NUE', 'Nuremberg Airport', 'Nuremberg', 'Germany', 'Europe/Berlin');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('LEJ', 'Leipzig/Halle Airport', 'Leipzig', 'Germany', 'Europe/Berlin');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('DRS', 'Dresden Airport', 'Dresden', 'Germany', 'Europe/Berlin');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('HAJ', 'Hanover Airport', 'Hanover', 'Germany', 'Europe/Berlin');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('FMO', 'Münster Osnabrück Airport', 'Münster', 'Germany', 'Europe/Berlin');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('BRE', 'Bremen Airport', 'Bremen', 'Germany', 'Europe/Berlin');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('SCN', 'Saarbrücken Airport', 'Saarbrücken', 'Germany', 'Europe/Berlin');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('ERF', 'Erfurt-Weimar Airport', 'Erfurt', 'Germany', 'Europe/Berlin');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('FDH', 'Friedrichshafen Airport', 'Friedrichshafen', 'Germany', 'Europe/Berlin');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('PEK', 'Beijing Capital International Airport', 'Beijing', 'China', 'Asia/Shanghai');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('PVG', 'Shanghai Pudong International Airport', 'Shanghai', 'China', 'Asia/Shanghai');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('HND', 'Tokyo Haneda Airport', 'Tokyo', 'Japan', 'Asia/Tokyo');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('NRT', 'Narita International Airport', 'Narita', 'Japan', 'Asia/Tokyo');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('ICN', 'Incheon International Airport', 'Seoul', 'South Korea', 'Asia/Seoul');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('SIN', 'Singapore Changi Airport', 'Singapore', 'Singapore', 'Asia/Singapore');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('BKK', 'Suvarnabhumi Airport', 'Bangkok', 'Thailand', 'Asia/Bangkok');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('KUL', 'Kuala Lumpur International Airport', 'Kuala Lumpur', 'Malaysia', 'Asia/Kuala_Lumpur');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('DEL', 'Indira Gandhi International Airport', 'Delhi', 'India', 'Asia/Kolkata');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('BOM', 'Chhatrapati Shivaji Maharaj International Airport', 'Mumbai', 'India', 'Asia/Kolkata');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('MNL', 'Ninoy Aquino International Airport', 'Manila', 'Philippines', 'Asia/Manila');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('HKG', 'Hong Kong International Airport', 'Hong Kong', 'Hong Kong', 'Asia/Hong_Kong');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('TPE', 'Taiwan Taoyuan International Airport', 'Taipei', 'Taiwan', 'Asia/Taipei');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('CGK', 'Soekarno-Hatta International Airport', 'Jakarta', 'Indonesia', 'Asia/Jakarta');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('DPS', 'Ngurah Rai International Airport', 'Bali', 'Indonesia', 'Asia/Makassar');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('SGN', 'Tan Son Nhat International Airport', 'Ho Chi Minh City', 'Vietnam', 'Asia/Ho_Chi_Minh');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('HAN', 'Noi Bai International Airport', 'Hanoi', 'Vietnam', 'Asia/Ho_Chi_Minh');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('DOH', 'Hamad International Airport', 'Doha', 'Qatar', 'Asia/Qatar');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('RUH', 'King Khalid International Airport', 'Riyadh', 'Saudi Arabia', 'Asia/Riyadh');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('JED', 'King Abdulaziz International Airport', 'Jeddah', 'Saudi Arabia', 'Asia/Riyadh');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('LHR', 'Heathrow Airport', 'London', 'United Kingdom', 'Europe/London');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('CDG', 'Charles de Gaulle Airport', 'Paris', 'France', 'Europe/Paris');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('FRA', 'Frankfurt Airport', 'Frankfurt', 'Germany', 'Europe/Berlin');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('AMS', 'Amsterdam Schiphol', 'Amsterdam', 'Netherlands', 'Europe/Amsterdam');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('MAD', 'Adolfo Suárez Madrid–Barajas', 'Madrid', 'Spain', 'Europe/Madrid');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('BCN', 'Barcelona–El Prat Airport', 'Barcelona', 'Spain', 'Europe/Madrid');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('VIE', 'Vienna International Airport', 'Vienna', 'Austria', 'Europe/Vienna');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('CPH', 'Copenhagen Airport', 'Copenhagen', 'Denmark', 'Europe/Copenhagen');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('ARN', 'Stockholm Arlanda Airport', 'Stockholm', 'Sweden', 'Europe/Stockholm');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('OSL', 'Oslo Gardermoen Airport', 'Oslo', 'Norway', 'Europe/Oslo');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('DUB', 'Dublin Airport', 'Dublin', 'Ireland', 'Europe/Dublin');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('BRU', 'Brussels Airport', 'Brussels', 'Belgium', 'Europe/Brussels');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('ZRH', 'Zurich Airport', 'Zurich', 'Switzerland', 'Europe/Zurich');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('PRG', 'Václav Havel Airport Prague', 'Prague', 'Czech Republic', 'Europe/Prague');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('WAW', 'Warsaw Chopin Airport', 'Warsaw', 'Poland', 'Europe/Warsaw');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('BUD', 'Budapest Airport', 'Budapest', 'Hungary', 'Europe/Budapest');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('ATH', 'Athens International Airport', 'Athens', 'Greece', 'Europe/Athens');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('HEL', 'Helsinki Airport', 'Helsinki', 'Finland', 'Europe/Helsinki');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('LIS', 'Lisbon Airport', 'Lisbon', 'Portugal', 'Europe/Lisbon');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('JFK', 'John F. Kennedy International', 'New York', 'USA', 'America/New_York');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('DXB', 'Dubai International Airport', 'Dubai', 'UAE', 'Asia/Dubai');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('SYD', 'Sydney Kingsford Smith Airport', 'Sydney', 'Australia', 'Australia/Sydney');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('CMB', 'Bandaranaike International Airport', 'Colombo', 'Sri Lanka', 'Asia/Colombo');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('LAX', 'Los Angeles International Airport', 'Los Angeles', 'USA', 'America/Los_Angeles');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('GRU', 'São Paulo–Guarulhos International Airport', 'São Paulo', 'Brazil', 'America/Sao_Paulo');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('JNB', 'O. R. Tambo International Airport', 'Johannesburg', 'South Africa', 'Africa/Johannesburg');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('MEX', 'Mexico City International Airport', 'Mexico City', 'Mexico', 'America/Mexico_City');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('YYZ', 'Toronto Pearson International Airport', 'Toronto', 'Canada', 'America/Toronto');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('EZE', 'Ministro Pistarini International Airport', 'Buenos Aires', 'Argentina', 'America/Argentina/Buenos_Aires');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('SVO', 'Sheremetyevo International Airport', 'Moscow', 'Russia', 'Europe/Moscow');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('DXB', 'Dubai International Airport', 'Dubai', 'UAE', 'Asia/Dubai');
INSERT INTO airport (airport_code, name, city, country, timezone) VALUES ('ICN', 'Incheon International Airport', 'Seoul', 'South Korea', 'Asia/Seoul');