-- db/init_permissions.sql

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO unicorn_admin;
GRANT USAGE ON SCHEMA public TO unicorn_admin;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO unicorn_admin;

GRANT CONNECT ON DATABASE operations TO unicorn_admin;
GRANT ALL PRIVILEGES ON DATABASE operations TO unicorn_admin;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL ON TABLES TO unicorn_admin;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL ON SEQUENCES TO unicorn_admin;
